import { DiagnosticStep, DimensionConfig } from "../types/diagnostic";

export const dimensionsConfig: Record<string, DimensionConfig> = {
  presenca: { id: "presenca", label: "Presença e Posicionamento", weight: 20 },
  processos: { id: "processos", label: "Processos e Automação", weight: 20 },
  dados: { id: "dados", label: "Dados e Gestão", weight: 20 },
  sistemas: { id: "sistemas", label: "Sistemas e Integrações", weight: 20 },
  comercial: { id: "comercial", label: "Comercial e Relacionamento", weight: 15 },
  seguranca: { id: "seguranca", label: "Segurança e Governança", weight: 5 },
};

export const diagnosticSteps: DiagnosticStep[] = [
  {
    id: "step1",
    title: "Perfil da Empresa",
    description: "Vamos começar conhecendo um pouco mais sobre o seu negócio.",
    questions: [
      { id: "nomeEmpresa", title: "Nome da empresa", type: "text", placeholder: "Sua Empresa" },
      { id: "segmento", title: "Segmento de atuação", type: "text", placeholder: "Ex: Tecnologia, Varejo..." },
      { id: "cidadeEstado", title: "Cidade e estado", type: "text", placeholder: "Ex: São Paulo, SP" },
      {
        id: "colaboradores",
        title: "Quantidade de colaboradores",
        type: "select",
        options: [
          { value: "1-5", label: "1 a 5" },
          { value: "6-20", label: "6 a 20" },
          { value: "21-50", label: "21 a 50" },
          { value: "51-100", label: "51 a 100" },
          { value: "101-500", label: "101 a 500" },
          { value: ">500", label: "Mais de 500" },
        ],
      },
      {
        id: "faturamentoMensal",
        title: "Faixa de faturamento mensal",
        type: "select",
        options: [
          { value: "ate-20k", label: "Até R$ 20 mil" },
          { value: "20k-50k", label: "R$ 20 mil a R$ 50 mil" },
          { value: "50k-100k", label: "R$ 50 mil a R$ 100 mil" },
          { value: "100k-300k", label: "R$ 100 mil a R$ 300 mil" },
          { value: "300k-1m", label: "R$ 300 mil a R$ 1 milhão" },
          { value: ">1m", label: "Acima de R$ 1 milhão" },
          { value: "nao-informar", label: "Prefiro não informar" },
        ],
      },
      {
        id: "modeloNegocio",
        title: "Principal modelo de negócio",
        type: "select",
        options: [
          { value: "servicos", label: "Serviços" },
          { value: "comercio", label: "Comércio" },
          { value: "industria", label: "Indústria" },
          { value: "assinatura", label: "Assinatura/Recorrência" },
          { value: "marketplace", label: "Marketplace" },
          { value: "infoprodutos", label: "Infoprodutos" },
          { value: "outro", label: "Outro" },
        ],
      },
      {
        id: "objetivoPrincipal",
        title: "Principal objetivo para os próximos 12 meses",
        type: "select",
        options: [
          { value: "aumentar-vendas", label: "Aumentar vendas" },
          { value: "reduzir-custos", label: "Reduzir custos" },
          { value: "ganhar-produtividade", label: "Ganhar produtividade" },
          { value: "organizar-processos", label: "Organizar processos" },
          { value: "melhorar-gestao", label: "Melhorar a gestão" },
          { value: "integrar-sistemas", label: "Integrar sistemas" },
          { value: "escalar-operacao", label: "Escalar a operação" },
          { value: "melhorar-presenca", label: "Melhorar presença digital" },
          { value: "lancar-produto", label: "Lançar um produto ou plataforma digital" },
        ],
      },
    ],
  },
  {
    id: "step2",
    title: "Presença e Posicionamento Digital",
    description: "Como a sua empresa se apresenta na internet e atrai clientes.",
    questions: [
      { id: "p1", title: "A empresa possui site profissional e atualizado?", type: "scale", dimension: "presenca", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "p2", title: "O site explica claramente o que a empresa faz, para quem e qual diferencial oferece?", type: "scale", dimension: "presenca", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "p3", title: "O site gera contatos ou oportunidades comerciais?", type: "scale", dimension: "presenca", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "p4", title: "O site funciona bem no celular?", type: "scale", dimension: "presenca", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "p5", title: "A empresa aparece de forma adequada em pesquisas no Google?", type: "scale", dimension: "presenca", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "p6", title: "A identidade visual transmite confiança e profissionalismo?", type: "scale", dimension: "presenca", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "p7", title: "A comunicação é consistente em site, redes sociais e materiais comerciais?", type: "scale", dimension: "presenca", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "p8", title: "Existem páginas ou conteúdos específicos para os principais serviços?", type: "scale", dimension: "presenca", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "p9", title: "A empresa acompanha acessos, conversões e origem dos contatos?", type: "scale", dimension: "presenca", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "p10", title: "Existe uma estratégia clara para transformar visitantes em leads?", type: "scale", dimension: "presenca", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      
      { id: "contatosSite", title: "Quantos contatos comerciais o site gera por mês?", type: "number", placeholder: "Ex: 50" },
      { id: "novosClientes", title: "Quantos novos clientes a empresa conquista por mês?", type: "number", placeholder: "Ex: 10" },
      { id: "ticketMedio", title: "Ticket médio aproximado (R$)", type: "currency", placeholder: "Ex: 1000" },
      { id: "taxaConversao", title: "Taxa de conversão estimada de oportunidade em cliente (%)", type: "percentage", placeholder: "Ex: 20" },
      { id: "investeTrafego", title: "A empresa investe em tráfego pago?", type: "select", options: [{ value: "sim", label: "Sim" }, { value: "nao", label: "Não" }] },
      { id: "utilizaCRM", title: "A empresa utiliza CRM?", type: "select", options: [{ value: "sim", label: "Sim" }, { value: "nao", label: "Não" }] },
    ],
  },
  {
    id: "step3",
    title: "Processos e Automação",
    description: "Avalie como as tarefas são executadas no dia a dia.",
    questions: [
      { id: "pr1", title: "Os principais processos estão documentados?", type: "scale", dimension: "processos", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "pr2", title: "Tarefas repetitivas são automatizadas?", type: "scale", dimension: "processos", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "pr3", title: "Informações são transferidas automaticamente entre ferramentas?", type: "scale", dimension: "processos", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "pr4", title: "A equipe evita digitação duplicada?", type: "scale", dimension: "processos", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "pr5", title: "Aprovações e solicitações têm fluxo definido?", type: "scale", dimension: "processos", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "pr6", title: "Clientes recebem atualizações automáticas?", type: "scale", dimension: "processos", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "pr7", title: "Propostas, contratos, cobranças ou relatórios são gerados com agilidade?", type: "scale", dimension: "processos", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "pr8", title: "A operação depende pouco de planilhas isoladas?", type: "scale", dimension: "processos", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "pr9", title: "A empresa consegue crescer sem aumentar custos na mesma proporção?", type: "scale", dimension: "processos", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "pr10", title: "Existem alertas para atrasos, falhas ou pendências?", type: "scale", dimension: "processos", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      
      { id: "pessoasTarefasRepetitivas", title: "Quantas pessoas executam tarefas administrativas ou repetitivas?", type: "number", placeholder: "Ex: 3" },
      { id: "horasSemanaTarefas", title: "Quantas horas por semana cada pessoa gasta nessas tarefas?", type: "number", placeholder: "Ex: 10" },
      { id: "custoMedioColaborador", title: "Custo médio mensal por colaborador envolvido (R$)", type: "currency", placeholder: "Ex: 3500" },
      { id: "percentualRetrabalho", title: "Percentual estimado de retrabalho (%)", type: "percentage", placeholder: "Ex: 15" },
      { id: "errosOperacionais", title: "Quantidade média de erros operacionais por mês", type: "number", placeholder: "Ex: 5" },
      { id: "custoMedioErro", title: "Custo médio estimado por erro, quando aplicável (R$)", type: "currency", placeholder: "Ex: 500" },
    ],
  },
  {
    id: "step4",
    title: "Dados, Indicadores e Tomada de Decisão",
    description: "Como a empresa acompanha resultados e toma decisões.",
    questions: [
      { id: "d1", title: "A liderança acompanha indicadores atualizados?", type: "scale", dimension: "dados", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "d2", title: "Existe um dashboard central?", type: "scale", dimension: "dados", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "d3", title: "Os dados são confiáveis?", type: "scale", dimension: "dados", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "d4", title: "É possível visualizar vendas, financeiro e operação sem consolidar planilhas manualmente?", type: "scale", dimension: "dados", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "d5", title: "Os gestores recebem alertas sobre desvios?", type: "scale", dimension: "dados", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "d6", title: "A empresa compara metas com resultados?", type: "scale", dimension: "dados", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "d7", title: "É possível identificar rapidamente produtos, clientes ou canais mais rentáveis?", type: "scale", dimension: "dados", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "d8", title: "As decisões são baseadas em dados?", type: "scale", dimension: "dados", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "d9", title: "Os relatórios são atualizados automaticamente?", type: "scale", dimension: "dados", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "d10", title: "A empresa consegue prever tendências, demanda ou fluxo de caixa?", type: "scale", dimension: "dados", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      
      { id: "horasRelatorios", title: "Quantas horas por mês são gastas montando relatórios?", type: "number", placeholder: "Ex: 20" },
      { id: "pessoasConsolidacao", title: "Quantas pessoas participam da consolidação de dados?", type: "number", placeholder: "Ex: 2" },
      { id: "impactoDecisoesTardias", title: "Qual o impacto percebido de decisões tardias?", type: "select", options: [{ value: "baixo", label: "Baixo" }, { value: "moderado", label: "Moderado" }, { value: "alto", label: "Alto" }, { value: "critico", label: "Crítico" }] },
    ],
  },
  {
    id: "step5",
    title: "Sistemas e Integrações",
    description: "Avalie a aderência das ferramentas que você utiliza.",
    questions: [
      { id: "s1", title: "A empresa utiliza sistemas adequados ao próprio processo?", type: "scale", dimension: "sistemas", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "s2", title: "Os sistemas utilizados conversam entre si?", type: "scale", dimension: "sistemas", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "s3", title: "A equipe encontra informações com facilidade?", type: "scale", dimension: "sistemas", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "s4", title: "Existem permissões de acesso por perfil?", type: "scale", dimension: "sistemas", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "s5", title: "Há histórico e rastreabilidade das ações?", type: "scale", dimension: "sistemas", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "s6", title: "O sistema atual suporta o crescimento da empresa?", type: "scale", dimension: "sistemas", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "s7", title: "Existem rotinas de backup e segurança?", type: "scale", dimension: "sistemas", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "s8", title: "Clientes, fornecedores ou parceiros possuem portais quando necessário?", type: "scale", dimension: "sistemas", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "s9", title: "A empresa consegue adaptar os sistemas quando o processo muda?", type: "scale", dimension: "sistemas", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "s10", title: "Existem APIs ou integrações com ferramentas importantes?", type: "scale", dimension: "sistemas", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      
      { id: "ferramentasDiferentes", title: "Quantas ferramentas diferentes são usadas no dia a dia?", type: "number", placeholder: "Ex: 5" },
      { id: "ferramentasSemIntegracao", title: "Quantas não possuem integração?", type: "number", placeholder: "Ex: 3" },
      { id: "sistemaLegado", title: "Existe algum sistema legado que limita a operação?", type: "select", options: [{ value: "sim", label: "Sim" }, { value: "nao", label: "Não" }] },
    ],
  },
  {
    id: "step6",
    title: "Comercial e Relacionamento",
    description: "Como você gerencia oportunidades e atende clientes.",
    questions: [
      { id: "c1", title: "Existe um processo comercial definido?", type: "scale", dimension: "comercial", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "c2", title: "Todos os contatos são registrados?", type: "scale", dimension: "comercial", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "c3", title: "Há acompanhamento das etapas do funil?", type: "scale", dimension: "comercial", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "c4", title: "A equipe faz follow-up de forma consistente?", type: "scale", dimension: "comercial", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "c5", title: "É possível identificar oportunidades paradas?", type: "scale", dimension: "comercial", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "c6", title: "Propostas são geradas e acompanhadas?", type: "scale", dimension: "comercial", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "c7", title: "O histórico de relacionamento fica centralizado?", type: "scale", dimension: "comercial", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "c8", title: "A empresa mede conversão por vendedor, canal e etapa?", type: "scale", dimension: "comercial", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "c9", title: "Há automações de atendimento e relacionamento?", type: "scale", dimension: "comercial", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "c10", title: "Existe acompanhamento do pós-venda e satisfação?", type: "scale", dimension: "comercial", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      
      { id: "leadsMensais", title: "Quantidade média de leads por mês", type: "number", placeholder: "Ex: 100" },
      { id: "leadsSemRetorno", title: "Percentual de leads sem retorno (%)", type: "percentage", placeholder: "Ex: 30" },
      { id: "propostasMensais", title: "Quantidade de propostas enviadas por mês", type: "number", placeholder: "Ex: 40" },
      { id: "propostasSemFollowUp", title: "Percentual de propostas sem follow-up (%)", type: "percentage", placeholder: "Ex: 20" },
      { id: "tempoCicloVenda", title: "Tempo médio do ciclo de venda (dias)", type: "number", placeholder: "Ex: 15" },
    ],
  },
  {
    id: "step7",
    title: "Segurança, Continuidade e Governança",
    description: "Como a empresa protege seus dados e garante a operação.",
    questions: [
      { id: "seg1", title: "A empresa possui controle de acesso por usuário?", type: "scale", dimension: "seguranca", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "seg2", title: "Ex-funcionários perdem os acessos rapidamente?", type: "scale", dimension: "seguranca", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "seg3", title: "Existe autenticação em dois fatores?", type: "scale", dimension: "seguranca", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "seg4", title: "Backups são realizados e testados?", type: "scale", dimension: "seguranca", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "seg5", title: "Dados sensíveis são armazenados de forma segura?", type: "scale", dimension: "seguranca", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "seg6", title: "A empresa possui política de privacidade?", type: "scale", dimension: "seguranca", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "seg7", title: "Existe controle sobre quem visualiza ou altera informações?", type: "scale", dimension: "seguranca", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "seg8", title: "Incidentes e erros são registrados?", type: "scale", dimension: "seguranca", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "seg9", title: "Há plano de continuidade em caso de falha?", type: "scale", dimension: "seguranca", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
      { id: "seg10", title: "A empresa conhece suas responsabilidades relacionadas à LGPD?", type: "scale", dimension: "seguranca", min: 0, max: 4, minLabel: "Não existe", maxLabel: "Funciona de forma estratégica" },
    ],
  },
  {
    id: "step8",
    title: "Prioridades e Percepção",
    description: "O que você busca resolver hoje.",
    questions: [
      { id: "problemaPrincipal", title: "Qual problema mais incomoda hoje?", type: "textarea", placeholder: "Descreva o que mais atrapalha a sua empresa..." },
      { id: "consequencia", title: "O que acontece se nada mudar nos próximos 12 meses?", type: "textarea", placeholder: "Ex: Perderemos mercado..." },
      { id: "projetoUrgente", title: "Qual projeto a empresa considera mais urgente?", type: "text", placeholder: "Ex: Implantação de um ERP" },
      {
        id: "tempoInicio",
        title: "Em quanto tempo gostaria de iniciar uma solução?",
        type: "select",
        options: [
          { value: "imediatamente", label: "Imediatamente" },
          { value: "30-dias", label: "Em até 30 dias" },
          { value: "2-3-meses", label: "Em 2 a 3 meses" },
          { value: "4-6-meses", label: "Em 4 a 6 meses" },
          { value: "pesquisando", label: "Ainda estou pesquisando" },
        ],
      },
      {
        id: "orcamento",
        title: "Existe orçamento previsto?",
        type: "select",
        options: [
          { value: "sim", label: "Sim" },
          { value: "definicao", label: "Em definição" },
          { value: "nao", label: "Ainda não" },
          { value: "conversar", label: "Prefiro conversar" },
        ],
      },
      { id: "decisores", title: "Quem participa da decisão?", type: "text", placeholder: "Ex: Sócios e Gestor de TI" },
      { id: "observacoes", title: "Observações", type: "textarea", placeholder: "Algo mais que gostaria de nos dizer?" },
    ],
  },
];
